export const FETCH_TODOS_END = 'FETCH_TODOS_END';
export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const SET_ERROR = 'SET_ERROR';
export const UPDATE_TODO_STATUS = 'UPDATE_TODO_STATUS';
export const ADD_NEW_TODO = 'ADD_NEW_TODO';


